export const siteConfig = {
  name: "Mory Coulibaly - Developpeur Fullstack Junior",
  authorName: "Mory Coulibaly",
  username: "morycoulibaly",
  description:
    "Portfolio de Mory Coulibaly, developpeur Fullstack Junior base a Abidjan, Cote d'Ivoire. Specialise en React, Vue.js, TypeScript, Laravel, NestJS, Flask, MySQL et applications web modernes.",
  url: "https://portfolio-mory-jade.vercel.app",
  links: {
    twitter: "https://x.com/morycoulibaly",
    github: "https://github.com/morycoulibaly",
    templateRepo: "https://github.com/morycoulibaly/portfolio",
  },
  ogImage: "https://portfolio-mory-jade.vercel.app/og-image.png",
  iconIco: "/favicon.ico",
  logoIcon: "/profile-img.jpg",
  keywords: [
    "Mory Coulibaly",
    "Developpeur Fullstack Junior",
    "Developpeur Web Abidjan",
    "Developpeur Fullstack Cote d'Ivoire",
    "React Developer",
    "Vue.js Developer",
    "TypeScript",
    "Laravel Developer",
    "NestJS Developer",
    "Flask Developer",
    "React Native Developer",
    "MySQL",
    "JavaScript",
    "HTML",
    "CSS",
    "Git",
    "GitHub",
    "Portfolio developpeur",
    "Stage developpeur web",
    "Alternance developpeur fullstack",
    "Developpeur junior Afrique francophone",
  ],
};
